# 应用名称
spring:
  application:
    name: encryption-spring-boot-sample
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'


# 应用服务 WEB 访问端口
server:
  port: 9000
  servlet:
    context-path: /encryption

# 加密配置
encryption:
  enable: true
  charset: 'UTF-8'
  # 是否开启加密在请求头中的key, 默认:Encryption
  enable-encryption-header: Encryption
# aes
#  algorithm: aes
#  configs:
#    secret-header-key: 'secret'
#    secret: 'OBDp6JYTRvgGmc6n'
#    iv: 'dHrALeTWPwlWgO6L'

# sm4 配置
  algorithm: sm4
  configs:
    secret-header-key: 'secret'
    secret: 'ABCDEFGHIJKL0123'

# sm2 配置
#  algorithm: sm2
#  configs:
#    secret-header-key: 'secret'
#    public-key: 'MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAETCmSFYmRhbEybwEs/iPQR2sb001588SW7UPJ2O7ZcKyzGieHyAcbwstRYDJvewm4Jv/DfNFQaqhjY9RGpAdRbw=='
#    private-key: 'MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgVGkJbAzsLrJUzxN3FECERhyOqcIkN6m2urMDejZ8TE2gCgYIKoEcz1UBgi2hRANCAARMKZIViZGFsTJvASz+I9BHaxvTTXnzxJbtQ8nY7tlwrLMaJ4fIBxvCy1FgMm97Cbgm/8N80VBqqGNj1EakB1Fv'
